#[[redirects]]
#  from = "/api/*"
#  to = "https://f649-3-239-33-213.ngrok-free.app/api/:splat"
#  status = 200
#  force = true
#  headers = { 
#    Access-Control-Allow-Credentials = "true", 
#    Access-Control-Allow-Origin = "https://together2.netlify.app" 
#  }
